### ISSUE TITLE
有办法在插件内获取到QQ号吗？

### ISSUE THREAD

**Issue by mofelee** [coldnight/pual_bot#11]

**Comment by mofelee** [comment]
之前用twqq做个一个打卡程序，要从数据库中判断是否有权记录qq，所以要判断qq号码，现在换到pual_bot之后，发现好像没办法获取到QQ号码。除了修改webqq.py文件之外就没法从from_uin获取到QQ号码了吗？

**Comment by mofelee** [comment]
忘了说了，是讨论组和qq群消息获取QQ号码

**Comment by coldnight** [comment]
https://github.com/coldnight/twqq/blob/master/twqq/hub.py#L289
插件内应应该可以用:

``` python
self.webqq.hub.get_account
```

访问到这个方法.  这个方法会返回QQ号, 但这个方法是同步的...

**Comment by coldnight** [comment]
讨论组的类型应该也是1

**Comment by mofelee** [comment]
恩，谢谢啦，我刚才看了一些时间代码也发现可以那样获取了，不过默认的0.17.0版本没有这个功能，0.24版本才有。。。

**Comment by coldnight** [comment]
之前有大规模的更改 twqq, 我怕影响旧程序的使用, 所以做了那个限制. pual_bot 跑在 0.24 上应该是没问题的.
