### ISSUE TITLE
安装twqq时setup.py 打开文件没有写明编码

### ISSUE THREAD

**Issue by hjw1991324** [coldnight/pual_bot#16]
安装twqq时报unicodeDecodeError:"gbk" ........ in position 12

**Comment by coldnight** [comment]
写明编码? 你是不是打开过文件然后把文件存储成 GBK编码了?  默认应该是 UTF-8 啊.

**Comment by hjw1991324** [comment]
没有呀，我就是你所说的按照easy_install twqq来安装的，并没有打开文件，是不是跟python版本有关，我使用的是python3

**Comment by coldnight** [comment]
twqq 虽然支持 Python3 , 但是会有些很蛋疼的 bug, 就是密码加密不通过.  最好还是用 python2

**Comment by hjw1991324** [comment]
好吧，我知道了，我试试用python2看有没有问题
