### ISSUE TITLE
为什么不能发送群消息？

### ISSUE THREAD

**Issue by Evyde** [coldnight/pual_bot#20]
私聊正常，群消息没反应。

**Comment by coldnight** [comment]
让你的程序跑一段时间, 或者在群聊天里喂点链接给他, 这个可能是因为 TX 的防垃圾信息机制.

**Comment by Evyde** [comment]
还是不行，注册了新账号也是如此。即使我这个帐号等级比较高，也还是不行。

---

Evenever
韩枫

--- 原始邮件 ---

发件人： "cold" notifications@github.com
已发： 2014年10月28日 上午10:15
收件人： "coldnight/pual_bot" pual_bot@noreply.github.com
抄送： "韩枫" life.app.hanfeng@hotmail.com
主题： Re: [pual_bot] 为什么不能发送群消息？ (#20)

让你的程序跑一段时间, 或者在群聊天里喂点链接给他, 这个可能是因为 TX 的防垃圾信息机制.

---
